CREATE TABLE IF NOT EXISTS candidates(
    id TEXT PRIMARY KEY,
    vote_qnt INTEGER DEFAULT 0,
    name TEXT
);

CREATE TABLE IF NOT EXISTS computerIP(
    ip TEXT PRIMARY KEY,
    voted BOOLEAN DEFAULT False
);